### ISSUE TITLE
focal.lmetrics output doesn't include 0 or 1

### ISSUE THREAD

**Issue by gregforcey** [jeffreyevans/spatialEco#11]
I'm trying to output a grid that captures that proportion of forest (value 1) in a landscape. The code below works to accomplish that; however, where the % forest is 0% or 100%, no data is written to the output grid. Is there anyway to output these values to the output grid like the moving window feature of FRAGSTATS does? Or do I have to use FRAGSTATS for this? Thanks. 
```r
land_forest <- raster("gis/moving_window/land_use_grid_clips/14.img")
land_forest_moving <- focal.lmetrics(land_forest, w = 11, land.value = 1,
                                       metric = "prop.landscape")
writeRaster(land_forest_moving, "gis/moving_window/outputs/14_forest.img")
```

**Comment by gregforcey** [comment]
Thanks Jeff, I will try the `focal` function directly. For the percentage of a landscape type, shouldn't the function have `length` in the numerator? Thus you are counting the number of cells of value 1 in the moving window and dividing by the total number of cells in the moving window.
```r
fun = function(x) {length(x[x==1]) / length(x) }
```

**Comment by jeffreyevans** [comment]
Sorry, responded on my phone and did not see that I left out the first length() call.

Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist
The Nature Conservancy | Global Lands Science Team
Affiliate Assistant Professor | Zoology & Physiology | University of Wyoming
Laramie, WY | jeffrey_evans@tnc.org | (970) 672-6766


________________________________

**Comment by jeffreyevans** [comment]
This function has been depreciated in leu of the landscapemetrics package
