### ISSUE TITLE
Problem with bandwidth calculation in sp.kde

### ISSUE THREAD

**Issue by sjewo** [jeffreyevans/spatialEco#13]
Dear Jeff, 

in the CRAN version of `spatialECO` is a bug in the bandwidth calculation for the `sp.kde` function: the estimation function doesn't make use of the coordinate pairs.

This bug is already fixed in commit 1603c1ed34a7f81a2d24186fb6a25ad7b54fb450.

**Comment by jeffreyevans** [comment]
This bug has been fixed with some function enhancements added in handling raster output.
