### ISSUE TITLE
Github repository not mentioned in package description

### ISSUE THREAD

**Issue by sjewo** [jeffreyevans/spatialEco#14]
Dear Jeff,

you might want to add a link to your github repo to the `DESCRIPTION` file so possible issues can be addressed here.

This line in `DESCRIPTION` will add a link in the CRAN man page:
`BugReports: https://github.com/jeffreyevans/spatialEco/issues`

**Comment by jeffreyevans** [comment]
Changed in new 1.2-0 version, propagating to CRAN mirrors now.
