### ISSUE TITLE
tpi annulus option

### ISSUE THREAD

**Issue by jasonMatney** [jeffreyevans/spatialEco#15]
Would it be possible to include an option for an annulus focal window in tpi.R? 

Looks like Jan Holstein has attempted this in his crecs pacakge - however I'd prefer to use spatialEco since its on CRAN: https://rdrr.io/github/janhoo/crecs/src/R/terrain.R

Thank you for your attention to this.

**Comment by jeffreyevans** [comment]
Jason,
I will add this as a development request but, not within the tpi function. When I get a change I will write a matrix function for deriving an annulus matrix that can then be passed to any focal function, including spatialEco functions that call for a window. I have to admit that using an annulus window in the TPI metric does give me pause. There are plenty of spatial processes that one can summarize by partialing out the previous scales using an annulus matrix, as opposed to a cumulative assessment using nested scales. However, given the nature of the TPI, along with other geomorphometric data, I fail to see what hypotheses one would be testing or what process would be represented. In the TPI, this would not represent a partialing function but rather a structural specification of the resulting metric. A weights matrix acting as a smoothing function, such as Gaussian Kernel or Wavelet, would make sense in decomposing variation across scales but an actual structural constraint to the kernel does not track with me. Perhaps you have some specific hypothesis that is just eluding me.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist / Biometrician
The Nature Conservancy | Global Lands Science
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>

**Comment by jasonMatney** [comment]
Thanks so much for considering this request Jeff, and apologies I didn't explain my reasoning more in my initial post. 

Essentially, I'm not testing a hypothesis, but instead attempting to visualize the relative geomorphic-grain of a given area at various landscape scales. I know that other software does this by ignoring some portion of the surrounding landscape in order to determine how similar or dissimilar the center point (grid cell) is to some window. My understanding is that an annulus is well supported in geomorphology [1]. 

Hope this clarifies this use-case.

[1] https://scholar.google.com/scholar?hl=en&as_sdt=0,47&q=tpi+annulus+geomorphology

**Comment by jeffreyevans** [comment]
Jason,
I have added a function “annulus.matrix” to the development version of spatialEco. You can install it from GitHub using remotes::install_github("jeffreyevans/spatialEco")

Please let me know if this will work for your applications or if you need clarification on the functions usage.

Best,
Jeff

**Comment by jasonMatney** [comment]
This is exactly the functionality I was looking to leverage alongside the rest of your package's functionality. Very much appreciate you taking the time to add this function. Thank you and I will be sure to spread the word!
