### ISSUE TITLE
Trasp function

### ISSUE THREAD

**Issue by Rapsodia86** [jeffreyevans/spatialEco#18]
Hi there, 
I think that there is missing parenthesis in the equation.
ORG:
"trasp <- function(x, ...) {  
  if (!inherits(x, "RasterLayer")) stop("MUST BE RasterLayer OBJECT")
    asp <- raster::terrain(x, out='aspect', unit='degrees') 
    return( raster::calc(asp, fun=function(x) { 1 - cos( (3.142/180)  *(x - 30) ) / 2 }, ... ) )"

Should not be?:

"trasp <- function(x, ...) {  
  if (!inherits(x, "RasterLayer")) stop("MUST BE RasterLayer OBJECT")
    asp <- raster::terrain(x, out='aspect', unit='degrees') 
    return( raster::calc(asp, fun=function(x) { (1 - cos( (3.142/180)  *(x - 30) )) / 2 }, ... ) )"

Best,
Monika

**Comment by jeffreyevans** [comment]
Monika,
Yep, that in fact was a mistake. Thank you for catching it! Is now fixed and will be a reported bug fix in the next CRAN release.

Best,
Jeff

**Comment by Rapsodia86** [comment]
Happy to help☺
Best regards,
Monika

Monika Anna Tomaszewska, M.S.
Ph.D. Candidate, Research Assistant
Geospatial Sciences Center of Excellence
Wecota Hall 115, Box 0506B
Brookings, SD 57007

www.sdstate.edu<http://www.sdstate.edu/>
[cid:image001.png@01D341BC.98DBE000]
[cid:image002.png@01D341BC.98DBE000]<https://www.facebook.com/SouthDakotaStateUniversity?fref=ts>   [cid:image003.png@01D341BC.98DBE000] <https://twitter.com/SDState>   [cid:image004.png@01D341BC.98DBE000] <https://www.youtube.com/user/SouthDakotaState>   [cid:image005.png@01D341BC.98DBE000] <http://instagram.com/sdstatepics>
