### ISSUE TITLE
package ‘spatialEco’ is not available (for R version 3.6.3)

### ISSUE THREAD

**Issue by momeni133** [jeffreyevans/spatialEco#20]
Hello everyone,
When I try to install the spatialEco package, I receive the below error in r:

> package ‘spatialEco’ is not available (for R version 3.6.3)

Do you know how can I install it?
Thanks,

**Comment by jeffreyevans** [comment]
Are you trying to install from CRAN? The spatialEco package is currently in an archived status. I received very short notice (14 days) that a dependency was being pulled from the repository and did not get updates posted soon enough (for two packages!). I am currently arguing with CRAN over the package being a new submission. It will be back on CRAN in the near future but they are being so difficult and nitpicky I am considering not distributing o CRAN any longer. They are really making me mad and I am certainly understanding why many developers are opting to not distribute their packages on the R repositories! That said, I will get this issue sorted out and the package back up on CRAN soon.

In the meantime you can install the development version from GitHub. Please install the devtools package for support of installing packages on GitHub. Please note that in the new version I am depreciating the `land.metrics` and `focal.lmetrics` functions. They are redundant with the landscapemetrics package and I do not want to introduce any disparity in results thus, allowing the landscapemetrics package to become the de facto standard for this type of analysis.

remotes::install_github("jeffreyevans/spatialEco")

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Protected Lands Science
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>

**Comment by momeni133** [comment]
Hi Jeff,
Thanks for your quick response.
I installed the package successfully.

Best,
Iman

**Comment by momeni133** [comment]
The problem has been resolved!
Thank you!
