### ISSUE TITLE
Regarding negative p-value for raster.kendall

### ISSUE THREAD

**Issue by adeel1997** [jeffreyevans/spatialEco#22]
Thank you for this great package. I was trying to run Mann Kendall test on the raster stack. While I was looking at the p-value of the output. I am getting negative values and many values greater than 1. I believe there is some issue in it. It would be great if you look into that. 

Thanks

**Comment by MARIASUAM** [comment]
Same here, p-values ranging between -3 and +3. Any hints?

**Comment by MARIASUAM** [comment]
Finally I used function MannKendall from package Kendall as I couldn't solve the issue with raster.kendall. The code I used, adapted from code found somewhere else, is:

fun_k <- function(x) {return(unlist(MannKendall(x)))}

kendall_output <- calc(my_stack, fun_k)
