### ISSUE TITLE
proximity.index

### ISSUE THREAD

**Issue by eaparras** [jeffreyevans/spatialEco#23]
Hi @jeffreyevans 

I just started to use your package to calculate proximity.index but I only get zeros after calculations. Do I need to transform the CRS to UTM?

Any help would be greatly appreciated
Cheers,
Edicson

pol.cqf = st_read("poly_sepa/cqf1.shp")
mapview(pol.cqf, layer = "Admin. level 0", color = "#000000") #All good
px.cqf1 <-proximity.index(pol.cqf, min.dist = 3)
px.cqf1
[1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[47] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
: 
:
# My polygon's information
> pol.cqf
class       : SpatialPolygonsDataFrame 
features    : 463 
extent      : -74.36225, -74.264, 4.5605, 4.6605  (xmin, xmax, ymin, ymax)
crs         : +proj=longlat +datum=WGS84 +no_defs 
variables   : 2
names       : DN,        area 
min values  :  1,     766.881 
max values  :  1, 46445029.38 

#Example polygon
> meuse_poly
class       : SpatialPolygonsDataFrame 
features    : 155 
extent      : 178562.3, 181429, 329677.5, 333650.5  (xmin, xmax, ymin, ymax)
crs         : NA 
variables   : 13
names       : cadmium, copper, lead, zinc,  elev,     dist, om, ffreq, soil, lime, landuse, dist.m,        LU 
min values  :     0.2,     14,   37,  113,  5.18,        0,  1,     1,    1,    0,      Aa,     10,    forest 
max values  :    18.1,    128,  654, 1839, 10.52, 0.880389, 17,     3,    3,    1,       W,   1000, nonforest

**Comment by jeffreyevans** [comment]
Your distance argument needs to be the same as your projection units (currently it is 3 which translates to something very small in DD). It is difficult to get accurate distances based on converting decimal degrees, using great circle distance. You really should reproject your data to a projection with distance units. The meuse data has a projection that is in meters.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Protected Lands Science
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>

**Comment by eaparras** [comment]
Hi Jeffrey, 

Thanks a lot for such a quick reply. Changed it to UTM and I did work perfectly, thanks again. 

I have now encountered another issue, when I change min.dist to any number I got the same result across:

Goal: To obtain proximity values for a focal patch at different radii to test for "Scale of Effects". 

px.cqf <-proximity.index(pol.cqf2,min.dist = 1)
px.cqf2 <-proximity.index(pol.cqf2,min.dist = 2)
identical(px.cqf, px.cqf2)
TRUE

Am I naively doing something wrong?

Any help would be greatly appreciated.

**Comment by jeffreyevans** [comment]
Well, the minimum distance argument (min.dist) will not have an effect if the actual minimum distances specified are invariant. Think of the min.dist creating a donut hole where everything in the hole is excluded. If there is nothing that meets that criteria than the result will not change until you hit a threshold that is relevant. Using 1 for min.dist self excludes a given source from the index.

You can see the minimum distance effect, using the muse_poly data from help, here:

for(i in seq(1,500, 25)) {
  cat("Proximity index for", i, "=", mean(proximity.index(meuse_poly,
      min.dist = i, max.dist = 1000)), "\n")
}

Best,
Jeff
