### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by semiscript** [jeffreyevans/spatialEco#24]
Hi, 

I am trying to install spatialEco package but I receive the following error message. I am working in Ubuntu with all the updates up-to-date.

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
* installing *source* package ‘rgeos’ ...
** package ‘rgeos’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
configure: rgeos: 0.5-5
checking for /usr/bin/svnversion... no
configure: svn revision: 640
checking for geos-config... no
no
configure: error: geos-config not found or not executable.
ERROR: configuration failed for package ‘rgeos’
* removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/rgeos’
Warning in install.packages :
  installation of package ‘rgeos’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘spdep’
* removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/spdep’
Warning in install.packages :
  installation of package ‘spdep’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘spdep’, ‘rgeos’ are not available for package ‘spatialEco’
* removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/spatialEco’
Warning in install.packages :
  installation of package ‘spatialEco’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpRUuLIk/downloaded_packages’

Thank you beforehand,
Jose Miguel

**Comment by jeffreyevans** [comment]
This looks like an error in installing package the dependencies: “sf”, “rgeos” and “spdep”. Try installing these packages first, from CRAN, and then install spatialEco. I know that there have been some issues with installing GEOS and GDAL through the sf, rgeos and rgdal package interfaces on certain OS so, you may need to do some online sleuthing to get these packages installed. If the issues persist you may need to try installing the development versions from source or submit a bug report to the maintainers of the packages.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Protected Lands Science
Visiting Professor | University of Wyoming | Zoology & Physiology
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>

From: semiscript ***@***.***>
Sent: Friday, March 12, 2021 5:34 AM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Install error (#24)


Hi,

I am trying to install spatialEco package but I receive the following error message. I am working in Ubuntu with all the updates up-to-date.

  *   installing source package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
  *   removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/sf’
Warning in install.packages :
installation of package ‘sf’ had non-zero exit status
  *   installing source package ‘rgeos’ ...
** package ‘rgeos’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
configure: rgeos: 0.5-5
checking for /usr/bin/svnversion... no
configure: svn revision: 640
checking for geos-config... no
no
configure: error: geos-config not found or not executable.
ERROR: configuration failed for package ‘rgeos’
  *   removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/rgeos’
Warning in install.packages :
installation of package ‘rgeos’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘spdep’
  *   removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/spdep’
Warning in install.packages :
installation of package ‘spdep’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘spdep’, ‘rgeos’ are not available for package ‘spatialEco’
  *   removing ‘/home/jose/R/x86_64-pc-linux-gnu-library/4.0/spatialEco’
Warning in install.packages :
installation of package ‘spatialEco’ had non-zero exit status

The downloaded source packages are in
‘/tmp/RtmpRUuLIk/downloaded_packages’

Thank you beforehand,
Jose Miguel
