### ISSUE TITLE
feature request? `only.holes`

### ISSUE THREAD

**Issue by eeholmes** [jeffreyevans/spatialEco#35]
Hi,

The `remove.holes()` functions is a handy utility function, but sometimes I need only the holes. A small change would all 'remove.holes()` to both remove or keep holes.

```
res <- lapply(1:length(xp), function(i) methods::slot(xp[[i]],  "Polygons")[!holes[[i]]])
```
to
```
res <- lapply(1:length(xp), function(i) methods::slot(xp[[i]],  "Polygons")[holes[[i]]])
```

Right now I just made my own `only.holes` function based on `remove.holes`.

Great package. Thanks!

**Comment by jeffreyevans** [comment]
Eli,
It sounds like you have a viable workaround so, I am not putting this on the top of my "to-do" list. However, I am, slowly, retooling the package to work with terra and sf class objects. When I rewrite this function I will add this feature request into the arguments. Thanks for making this request, it does seem like it would be a useful option.

**Comment by jeffreyevans** [comment]
This is in incorporated into the new version of the function, specific to sf class objects. The argument only.holes = TRUE will return an sf POLYGON object containing only the holes in the input feature class otherwise the holes will be erased.
