### ISSUE TITLE
Error between different packages with MannKendall test

### ISSUE THREAD

**Issue by georgeboldeanu** [jeffreyevans/spatialEco#36]
Cheers!

I tested recently the MannKendall trend test. If on a limited dataset from one pixel (extracted on some point) I got the same results with 3 test from 3 different packages, when I try to compute the test on the whole rasters I got wrong values. Just the tau test value is the same with the other tests, and somehow the Pvalue is the one for the Z test value and the Intercept value the one for the Pvalue. 
Anyone got any idea what can it be?

A transfer link for the raster test data: https://we.tl/t-FomZSMXStk

Test data for the for the different trend test applied in R. 
[test.csv](https://github.com/jeffreyevans/spatialEco/files/7245127/test.csv)

Screenshot from QGIS with all the values for the interest raster resulted after MannKendall test
![qgis values](https://user-images.githubusercontent.com/34105846/135112594-f0ec4e84-f9d6-439b-824c-aebbf2fc97a2.PNG)

Screenshot with the results from R and the example code with all the packages imported.
![mann](https://user-images.githubusercontent.com/34105846/135112596-345a6ae0-5ad0-4db9-8999-c7048c263a49.PNG)

R snippet to apply MannKendall test from different packages
```
library(stringi)
library(Kendall)
library(dplyr)
library(trend)
library(EnvStats)



data22<- read.csv ("E:/stats_tile/test.csv", encoding = "UTF-8")##locale=locale(encoding = "UTF-8"))

test_1<-mk.test(data22$valori)
test_2<-MannKendall(data22$valori)
test_3<-spatialEco::kendall(data22$valori)
test_4<-EnvStats::kendallTrendTest(data22$valori)

test_1
test_2
test_3
test_4
```

**Comment by jeffreyevans** [comment]
I have no idea as to why `trend::mk.test` is producing such different results but, the spatialEco, EnvStats and kendall packages are all returning comparable tau, slope and intercept values so, based on this agreement I would look towards issues in the trend package.
