### ISSUE TITLE
Add 2 independent variables

### ISSUE THREAD

**Issue by aniluap5** [jeffreyevans/spatialEco#4]
Hi,
Currently, I am working on spatial downscaling of LST data with the use of more than one explanatory variables. Could you tell me in what way I could implement more independent variables as 'x'?

Thank you,

Paulina

**Comment by jeffreyevans** [comment]
If the argument for x represents a raster stack, with more than one raster, it is automatically assumed that there are multiple independent variables. I will add this clarification to the help in the next release.

Best,
Jeff


Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist

The Nature Conservancy | Global Lands Science Team

Visiting Professor | University of Wyoming | Zoology & Physiology

Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>

**Comment by aniluap5** [comment]
Hi Jeffrey,

Everything works very well. Thanks for your help.

Best,
Paulina

**Comment by aniluap5** [comment]
Hi Jeff,

I found that 2 of my images had many NA values. After exclusion of this
dataset everything was calculated in proper way. Thank you a lot for your
help.


Best,

Paulina
