### ISSUE TITLE
st_geos_binop error in spatialEco::point.in.poly

### ISSUE THREAD

**Issue by sebfournier95** [jeffreyevans/spatialEco#45]
Code :

track_data <- read_excel(paste(tracks_dir, tracks, sep = "/"))
check <- tracks
skipper <- file_path_sans_ext(tracks)

track_lats <- (track_data[1:nrow(track_data)- 1, "latitude"] + track_data[2:nrow(track_data), "latitude"]) / 2
track_lons <- (track_data[1:nrow(track_data)- 1, "longitude"] + track_data[2:nrow(track_data), "longitude"]) / 2

track_delta_ts <- track_data[1:nrow(track_data)- 1, "Time_s"]
track_speeds <- (track_data[1:nrow(track_data)- 1, "speed_kts"]) * 1.852 / 3.6

track_analysis_mk <- data.frame(track_lats, track_lons, track_delta_ts, track_speeds)
long <- track_analysis_mk$longitude
lat <- track_analysis_mk$latitude

sp::coordinates(track_analysis_mk) <- c("longitude", "latitude")
sp::proj4string(track_analysis_mk) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
track_analysis_mk <- sp::spTransform(track_analysis_mk, proj4string(SCANS_3))
track_analysis_mk_SCANS_3 <- spatialEco::point.in.poly(track_analysis_mk, SCANS_3, sp = TRUE, duplicate = TRUE)

Error : 

Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared,  (Simulation_VALS_2008-2021_for_PC.R#198): st_crs(x) == st_crs(y) is not TRUE
Show stack trace

PS: 

track_analysis_mk is a SpatialPointsDataFrame
SCANS is a SpatialPolygonDataFrame

I run the code on a Window workstation and I have this error. If I run the same code on my macOS, the code runs well.

**Comment by jeffreyevans** [comment]
To avoid duplication, this function has been depreciated in leu of `sf::st_intersection`. As it was a useful wrapper, expanding capacity, with sp it is now redundant with sf functions. This is effective as of spatialEco 2.0-0
