### ISSUE TITLE
Bug in curvature function for mcnab type

### ISSUE THREAD

**Issue by avkoehl** [jeffreyevans/spatialEco#55]
Hi, I am helping a lab mate with some code and we're having issues with McNab's curvature metric. It seems to always return values equal to the input raster. Am I missing something? 

```
library("terra")
library("spatialEco")

dem = terra::rast(system.file("extdata", "elev.tif", package = "spatialEco"))
mcnab = spatialEco::curvature(dem, type="mcnab")

terra::plot(dem-mcnab)
```

<img width="845" alt="Screenshot 2023-05-09 at 12 40 58 PM" src="https://github.com/jeffreyevans/spatialEco/assets/15973367/fb744363-3f09-4188-9491-5b0bab701454">

```
sessionInfo()
```
<img width="698" alt="Screenshot 2023-05-09 at 12 42 22 PM" src="https://github.com/jeffreyevans/spatialEco/assets/15973367/61e5b5e9-8d5f-404e-8874-60a4cfb32a4b">

**Comment by jeffreyevans** [comment]
I just pushed an update to the development GitHub version that fixes this bug.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Global Protect, Science
Visiting Professor | University of Wyoming | Ecosystem Sciences
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>
ORCID-ID 0000-0002-5533-7044
TNC Biography<https://www.nature.org/en-us/about-us/who-we-are/our-people/jeff-evans/> – Google Scholar<https://scholar.google.com/citations?user=FwU_ppgAAAAJ&hl=en>

From: Arthur Koehl ***@***.***>
Sent: Tuesday, May 9, 2023 1:49 PM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Bug in curvature function for mcnab type (Issue #55)


Hi, I am helping a lab mate with some code and we're having issues with McNab's curvature metric. It seems to always return values equal to the input raster. Am I missing something?

library("terra")

library("spatialEco")



dem = terra::rast(system.file("extdata", "elev.tif", package = "spatialEco"))

mcnab = spatialEco::curvature(dem, type="mcnab")



terra::plot(dem-mcnab)
[Screenshot 2023-05-09 at 12 40 58 PM]<https://user-images.githubusercontent.com/15973367/237203132-fb744363-3f09-4188-9491-5b0bab701454.png>

sessionInfo()
[Screenshot 2023-05-09 at 12 42 22 PM]<https://user-images.githubusercontent.com/15973367/237203434-61e5b5e9-8d5f-404e-8874-60a4cfb32a4b.png>
