### ISSUE TITLE
wt.centroid and tibbles

### ISSUE THREAD

**Issue by andrewgustar** [jeffreyevans/spatialEco#56]
I have just answered this question on stackoverflow https://stackoverflow.com/questions/76334169/how-to-compute-the-weighted-centroid-of-multiple-st-points-with-the-spatialeco-p .

There seems to be a problem in the code for `wt.centroid` as the method it uses to extract the column of weights does not work if the input `sf` object is also a tibble. It seems that `sf::st_drop_geometry` behaves differently for dataframes and tibbles (so perhaps I ought to be raising the issue there).

**Comment by jeffreyevans** [comment]
Andrew,
Thank you for letting me know. I will post a bug fix next week and push a new development version. I have not really built in support for tibble's so, will look at some other functions to see if this issues arises elseware.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Global Protect, Science
Visiting Professor | University of Wyoming | Ecosystem Sciences
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>
ORCID-ID 0000-0002-5533-7044
TNC Biography<https://www.nature.org/en-us/about-us/who-we-are/our-people/jeff-evans/> - Google Scholar<https://scholar.google.com/citations?user=FwU_ppgAAAAJ&hl=en>

From: andrewgustar ***@***.***>
Sent: Thursday, May 25, 2023 12:41 PM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] wt.centroid and tibbles (Issue #56)


I have just answered this question on stackoverflow https://stackoverflow.com/questions/76334169/how-to-compute-the-weighted-centroid-of-multiple-st-points-with-the-spatialeco-p<https://stackoverflow.com/questions/76334169/how-to-compute-the-weighted-centroid-of-multiple-st-points-with-the-spatialeco-p> .

There seems to be a problem in the code for wt.centroid as the method it uses to extract the column of weights does not work if the input sf object is also a tibble. It seems that sf::st_drop_geometry behaves differently for dataframes and tibbles (so perhaps I ought to be raising the issue there).

-

**Comment by andrewgustar** [comment]
Thanks Jeff. Hopefully it is just a case of adding an `unlist` here and there.

All the best

Andrew

**Comment by jeffreyevans** [comment]
It was a simple fix of pulling the weights column using `as.data.frame(sf::st_drop_geometry(x[,p]))[,1]`
