### ISSUE TITLE
Error in raster.kendall package

### ISSUE THREAD

**Issue by venkateshkolluru95** [jeffreyevans/spatialEco#58]
I have a series of rasters (16 files) loaded as tiff files with SpatRaster format. However, while running the code I am getting an error stating 'Error in kendall(y) : The Kendall Tau should have at least 6 observations'. I have opened the loaded variable and was able to see 16 files. Could you please help resolve the issue?

Thanks!

**Comment by jeffreyevans** [comment]
There are not enough observations in some of the pixel vectors. I have added an argument that results in NA's rather than an error.
