### ISSUE TITLE
crossCorrelation - spatial weight matrix is not symmetric by default

### ISSUE THREAD

**Issue by orcu** [jeffreyevans/spatialEco#6]
The reference states the weight matrix is symmetric. (Chen pg.3) The function row-standardizes when scale.matrix is set to true, which violates the assumption. Possible fix is unity standardization as in w <- as.matrix(w/sum(w)).

**Comment by jeffreyevans** [comment]
The scale.matrix argument is only used when a matrix is provided. The row-standardization was following advice by Rodger Bivand in regard to how neighbor matrices are derived in spdep. I however changed it to standardization using [w/sum(w)] which is how the matrices are standardized if derived internally.

Best,
Jeff


Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist

The Nature Conservancy | Global Lands Science Team

Visiting Professor | University of Wyoming | Zoology & Physology

Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>
