### ISSUE TITLE
breeding.density - "implicit list embedding of S4 objects is deprecated"

### ISSUE THREAD

**Issue by jcarlis3** [jeffreyevans/spatialEco#9]
Hi @jeffreyevans,

Looks like changes to R as of version 3.3.0 introduced an annoying warning to `breeding.density`.  Minor, but looks to be a one-liner fix.

Best,
Jason

**Reproduce issue**
The issue can be reproduced using the help doc example for `breeding.density` (I'm using R version 3.5.2 and platform i386-w64-mingw32/i386 (32-bit)).  The returned object appears correct, but >= 50 warnings are raised:
```
In `[<-`(`*tmp*`, i, value = sp::Polygons(list(polys[[i]]),  ... :
  implicit list embedding of S4 objects is deprecated
```

**Cause**
The warning appears to be caused by a change to how R handles S4 objects beginning in R version 3.3.0.  [Link](https://stat.ethz.ch/pipermail/r-devel/2016-May/072730.html) to more info.

**Solution**
A bit of testing suggests the warning can be removed by modifying line 83 of the function (as of spatialEco 1.1.1) to use double brackets:

Single brackets, as in line 83 of breeding.density in spatialEco version 1.1.1
`pl[i] <- sp::Polygons(list(polys[[i]]), i)`

Double brackets, modified to comply with R>3.3.0 S4 standards, eliminates warning
`pl[[i]] <- sp::Polygons(list(polys[[i]]), i)`

**Comment by jeffreyevans** [comment]
Thanks for the heads up, will fix shortly.

-Jeff
